version: '3.8'

services:
  springboot-app:
    image: yashguj20/spring-boot-todo-app
    container_name: springboot-todo-app
    ports:
      - "8081:8080"  # Map container's 8080 to host's 8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
